<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>h264_image_transport</name>
  <version>0.0.1</version>
  <description>The h264_image_transport package</description>

  <maintainer email="adl@ut.ee">University of Tartu Autonomous Driving Lab</maintainer>
  <author email="maxandre.ogeret@mogrobotics.com">Maxandre Ogeret</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <build_depend>libavcodec-dev</build_depend>
  <build_depend>libavutil-dev</build_depend>
  <build_depend>libswscale-dev</build_depend>
  <build_depend>libx264-dev</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
